<?php

class EpisodeTableSeeder extends Seeder {

    /**
     * Auto generated seed file
     *
     * @return void
     */
    public function run()
    {
        \DB::table('episode')->delete();
        
        \DB::table('episode')->insert(array (
            0 => 
            array (
                'id' => 85751,
                'series_id' => 72449,
                'season' => 1,
                'episode' => 2,
                'airdate' => '1997-07-27 00:00:00',
            'name' => 'Children of the Gods (2)',
                'description' => 'Colonel O\'Neill, leading the new SG-1, track Apophis back to the planet Chulak to rescue Sha\'re and Skaara, and befriend one of Apophis\' Jaffa guards.',
                'image' => 'none',
                'created_at' => '2015-02-20 15:54:22',
                'updated_at' => '2015-02-20 15:54:22',
            ),
            1 => 
            array (
                'id' => 85752,
                'series_id' => 72449,
                'season' => 1,
                'episode' => 3,
                'airdate' => '1997-08-01 00:00:00',
                'name' => 'The Enemy Within',
                'description' => 'Major Kawalsky is possessed by a Goa\'uld, and the SGC must find a way to remove it without killing him.',
                'image' => 'none',
                'created_at' => '2015-02-20 15:54:22',
                'updated_at' => '2015-02-20 15:54:22',
            ),
            2 => 
            array (
                'id' => 85753,
                'series_id' => 72449,
                'season' => 1,
                'episode' => 4,
                'airdate' => '1997-08-08 00:00:00',
                'name' => 'Emancipation',
                'description' => 'An alien civilization is forced to reconsider their views on women when Carter rebels against their social customs.',
                'image' => 'none',
                'created_at' => '2015-02-20 15:54:22',
                'updated_at' => '2015-02-20 15:54:22',
            ),
            3 => 
            array (
                'id' => 85754,
                'series_id' => 72449,
                'season' => 1,
                'episode' => 5,
                'airdate' => '1997-08-15 00:00:00',
                'name' => 'The Broca Divide',
                'description' => 'Members of SG-1 become infected with an alien virus that turns them into primitive beings. Dr. Fraiser must find a cure to save the team and the alien population from whom it was contracted.',
                'image' => 'none',
                'created_at' => '2015-02-20 15:54:23',
                'updated_at' => '2015-02-20 15:54:23',
            ),
            4 => 
            array (
                'id' => 85755,
                'series_id' => 72449,
                'season' => 1,
                'episode' => 6,
                'airdate' => '1997-08-22 00:00:00',
                'name' => 'The First Commandment',
                'description' => 'SG-1 must stop a renegade Stargate commander, who has gone mad and set himself up as a god on an alien planet.',
                'image' => 'none',
                'created_at' => '2015-02-20 15:54:23',
                'updated_at' => '2015-02-20 15:54:23',
            ),
            5 => 
            array (
                'id' => 85756,
                'series_id' => 72449,
                'season' => 1,
                'episode' => 7,
                'airdate' => '1997-08-29 00:00:00',
                'name' => 'Cold Lazarus',
                'description' => 'During an off-world assignment, Jack is struck down by energy from a blue crystal... which creates a duplicate of him that returns to Earth in Jack\'s place.',
                'image' => 'none',
                'created_at' => '2015-02-20 15:54:23',
                'updated_at' => '2015-02-20 15:54:23',
            ),
            6 => 
            array (
                'id' => 85757,
                'series_id' => 72449,
                'season' => 1,
                'episode' => 8,
                'airdate' => '1997-09-12 00:00:00',
                'name' => 'The Nox',
                'description' => 'Pressed by the government to acquire new technologies, SG-1 is led to a world inhabited by a seemingly primative race. When Apophis arrives, SG-1 ambush him with disasterous consequences.',
                'image' => 'none',
                'created_at' => '2015-02-20 15:54:23',
                'updated_at' => '2015-02-20 15:54:23',
            ),
            7 => 
            array (
                'id' => 85758,
                'series_id' => 72449,
                'season' => 1,
                'episode' => 9,
                'airdate' => '1997-09-19 00:00:00',
                'name' => 'Brief Candle',
                'description' => 'SG-1 discovers a race of attractive people who age extremely rapidly. The situation becomes personal when O\'Neill begins to suffer from the same accelerated aging, and must live out the rest of his life on the planet.',
                'image' => 'none',
                'created_at' => '2015-02-20 15:54:23',
                'updated_at' => '2015-02-20 15:54:23',
            ),
            8 => 
            array (
                'id' => 85759,
                'series_id' => 72449,
                'season' => 1,
                'episode' => 10,
                'airdate' => '1997-09-26 00:00:00',
                'name' => 'Thor\'s Hammer',
                'description' => 'Teal\'c and O\'Neill are transported to an underground cage designed by the Asgard to protect an alien world from the Goa\'uld. ',
                'image' => 'none',
                'created_at' => '2015-02-20 15:54:23',
                'updated_at' => '2015-02-20 15:54:23',
            ),
            9 => 
            array (
                'id' => 85760,
                'series_id' => 72449,
                'season' => 1,
                'episode' => 11,
                'airdate' => '1997-10-03 00:00:00',
                'name' => 'The Torment of Tantalus',
                'description' => 'SG-1 tracks down Catherine Langford\'s fiance, who took the first Stargate trip in 1945, and discovers an ancient meeting hall that may hold the secrets of the universe itself.',
                'image' => 'none',
                'created_at' => '2015-02-20 15:54:23',
                'updated_at' => '2015-02-20 15:54:23',
            ),
            10 => 
            array (
                'id' => 85761,
                'series_id' => 72449,
                'season' => 1,
                'episode' => 12,
                'airdate' => '1997-10-10 00:00:00',
                'name' => 'Bloodlines',
                'description' => 'Teal\'c returns to Chulak to stop his people from implanting his son with a larval Goa\'uld.',
                'image' => 'none',
                'created_at' => '2015-02-20 15:54:23',
                'updated_at' => '2015-02-20 15:54:23',
            ),
            11 => 
            array (
                'id' => 85762,
                'series_id' => 72449,
                'season' => 1,
                'episode' => 13,
                'airdate' => '1997-10-17 00:00:00',
                'name' => 'Fire and Water',
                'description' => 'Daniel is taken captive by an alien with a hidden agenda, while SG-1 is made to believe he is dead.',
                'image' => 'none',
                'created_at' => '2015-02-20 15:54:23',
                'updated_at' => '2015-02-20 15:54:23',
            ),
            12 => 
            array (
                'id' => 85763,
                'series_id' => 72449,
                'season' => 1,
                'episode' => 14,
                'airdate' => '1997-10-24 00:00:00',
                'name' => 'Hathor',
                'description' => 'The banished Goa\'uld Hathor is found in an ancient sarcophagus Earth, and takes over the S.G.C. with hopes of raising a new army against the System Lords.',
                'image' => 'none',
                'created_at' => '2015-02-20 15:54:23',
                'updated_at' => '2015-02-20 15:54:23',
            ),
            13 => 
            array (
                'id' => 85764,
                'series_id' => 72449,
                'season' => 1,
                'episode' => 15,
                'airdate' => '1997-10-31 00:00:00',
                'name' => 'Singularity',
                'description' => 'A mysterious affliction wipes out the entire population of a planet, plus an SG team -- except for one young girl. Carter befriends her, but learns that she is being used by the Goa\'uld.',
                'image' => 'none',
                'created_at' => '2015-02-20 15:54:23',
                'updated_at' => '2015-02-20 15:54:23',
            ),
            14 => 
            array (
                'id' => 85765,
                'series_id' => 72449,
                'season' => 1,
                'episode' => 16,
                'airdate' => '1998-01-23 00:00:00',
                'name' => 'Cor-Ai',
                'description' => 'Teal\'c must stand trial for a crime committed while he served as first prime of Apophis when a villager on an alien world identifies him as the Jaffa who killed his father.',
                'image' => 'none',
                'created_at' => '2015-02-20 15:54:23',
                'updated_at' => '2015-02-20 15:54:23',
            ),
            15 => 
            array (
                'id' => 85766,
                'series_id' => 72449,
                'season' => 1,
                'episode' => 17,
                'airdate' => '1998-01-30 00:00:00',
                'name' => 'Enigma',
                'description' => 'The SG-1 team rescues a group of advanced humans from a planet near destruction, and must find a new home for the refugees before the Pentagon gets their hands on them.',
                'image' => 'none',
                'created_at' => '2015-02-20 15:54:23',
                'updated_at' => '2015-02-20 15:54:23',
            ),
            16 => 
            array (
                'id' => 85767,
                'series_id' => 72449,
                'season' => 1,
                'episode' => 18,
                'airdate' => '1998-02-06 00:00:00',
                'name' => 'Solitudes',
                'description' => 'Colonel O\'Neill and Captain Carter are separated from Jackson and Teal\'c during a Stargate journey, and are trapped on a desolate ice world with no way of escape.',
                'image' => 'none',
                'created_at' => '2015-02-20 15:54:23',
                'updated_at' => '2015-02-20 15:54:23',
            ),
            17 => 
            array (
                'id' => 85768,
                'series_id' => 72449,
                'season' => 1,
                'episode' => 19,
                'airdate' => '1998-02-13 00:00:00',
                'name' => 'Tin Man',
                'description' => 'The members of SG-1 arrive on P3X-989 and are knocked unconscious.  They wake up and return to Earth only to find that they are not quite themselves.',
                'image' => 'none',
                'created_at' => '2015-02-20 15:54:23',
                'updated_at' => '2015-02-20 15:54:23',
            ),
            18 => 
            array (
                'id' => 85769,
                'series_id' => 72449,
                'season' => 1,
                'episode' => 20,
                'airdate' => '1998-02-20 00:00:00',
                'name' => 'There But For the Grace of God',
                'description' => 'An alien artifact transports Daniel to an alternate reality, where he is not a part of the Stargate program and the Goa\'uld -- led by Teal\'c -- are invading Earth.',
                'image' => 'none',
                'created_at' => '2015-02-20 15:54:23',
                'updated_at' => '2015-02-20 15:54:23',
            ),
            19 => 
            array (
                'id' => 85770,
                'series_id' => 72449,
                'season' => 1,
                'episode' => 21,
                'airdate' => '1998-02-27 00:00:00',
                'name' => 'Politics',
                'description' => 'Senator Kinsey arrives at the SGC to investigate the program and determine whether the great drain on the U.S. budget is worthwhile, prompting the team to recall missions from the past year.',
                'image' => 'none',
                'created_at' => '2015-02-20 15:54:23',
                'updated_at' => '2015-02-20 15:54:23',
            ),
            20 => 
            array (
                'id' => 85771,
                'series_id' => 72449,
                'season' => 1,
                'episode' => 22,
                'airdate' => '1998-03-06 00:00:00',
                'name' => 'Within the Serpent\'s Grasp',
                'description' => 'SG-1 escapes through the Stargate before it is shut down, and learns that Daniel\'s alternate reality vision is true: Apophis is moving to attack Earth from above. The team must stop Apophis and his son, Klorel, who inhabits the body of their friend Skaara.',
                'image' => 'none',
                'created_at' => '2015-02-20 15:54:23',
                'updated_at' => '2015-02-20 15:54:23',
            ),
            21 => 
            array (
                'id' => 85773,
                'series_id' => 72449,
                'season' => 2,
                'episode' => 1,
                'airdate' => '1998-06-26 00:00:00',
                'name' => 'The Serpent\'s Lair',
                'description' => 'With SG-1 trapped on Klorel\'s ship, it seems that Earth is doomed as the Pyramid Ships prepare to destroy Earth.',
                'image' => 'none',
                'created_at' => '2015-02-20 15:54:23',
                'updated_at' => '2015-02-20 15:54:23',
            ),
            22 => 
            array (
                'id' => 85774,
                'series_id' => 72449,
                'season' => 2,
                'episode' => 2,
                'airdate' => '1998-07-03 00:00:00',
                'name' => 'In the Line of Duty',
                'description' => 'Carter is possessed by a Goa\'uld who claims to be an enemy of the System Lords. ',
                'image' => 'none',
                'created_at' => '2015-02-20 15:54:24',
                'updated_at' => '2015-02-20 15:54:24',
            ),
            23 => 
            array (
                'id' => 85775,
                'series_id' => 72449,
                'season' => 2,
                'episode' => 3,
                'airdate' => '1998-07-10 00:00:00',
                'name' => 'Prisoners',
                'description' => 'SG-1 is put on trial and exiled to a prison world, where a woman maintains a strange control over her fellow prisoners.',
                'image' => 'none',
                'created_at' => '2015-02-20 15:54:24',
                'updated_at' => '2015-02-20 15:54:24',
            ),
            24 => 
            array (
                'id' => 85776,
                'series_id' => 72449,
                'season' => 2,
                'episode' => 4,
                'airdate' => '1998-07-17 00:00:00',
                'name' => 'The Gamekeeper',
                'description' => 'SG-1 is imprisoned in a virtual reality realm and forced to relive the worst moments of their lives over and over.',
                'image' => 'none',
                'created_at' => '2015-02-20 15:54:24',
                'updated_at' => '2015-02-20 15:54:24',
            ),
            25 => 
            array (
                'id' => 85777,
                'series_id' => 72449,
                'season' => 2,
                'episode' => 5,
                'airdate' => '1998-07-24 00:00:00',
                'name' => 'Need',
                'description' => 'Jackson becomes addicted to the effects of a Goa\'uld sarcophagus, and falls for the planet\'s manipulative princess.',
                'image' => 'none',
                'created_at' => '2015-02-20 15:54:24',
                'updated_at' => '2015-02-20 15:54:24',
            ),
            26 => 
            array (
                'id' => 85778,
                'series_id' => 72449,
                'season' => 2,
                'episode' => 6,
                'airdate' => '1998-07-31 00:00:00',
                'name' => 'Thor\'s Chariot',
                'description' => 'SG-1 returns to Cimmeria, and finds that without protection from the Asgard the planet has been invaded by the Goa\'uld.',
                'image' => 'none',
                'created_at' => '2015-02-20 15:54:24',
                'updated_at' => '2015-02-20 15:54:24',
            ),
            27 => 
            array (
                'id' => 85779,
                'series_id' => 72449,
                'season' => 2,
                'episode' => 7,
                'airdate' => '1998-08-07 00:00:00',
                'name' => 'Message in a Bottle',
                'description' => 'SG-1 discovers an ancient artifact that takes O\'Neill and the S.G.C. hostage.',
                'image' => 'none',
                'created_at' => '2015-02-20 15:54:24',
                'updated_at' => '2015-02-20 15:54:24',
            ),
            28 => 
            array (
                'id' => 85780,
                'series_id' => 72449,
                'season' => 2,
                'episode' => 8,
                'airdate' => '1998-08-14 00:00:00',
                'name' => 'Family',
                'description' => 'The SG-1 team attempt to rescue Teal\'c\'s son, who has been kidnapped and brainwashed by Apophis. Teal\'c learns disturbing news about his wife.',
                'image' => 'none',
                'created_at' => '2015-02-20 15:54:24',
                'updated_at' => '2015-02-20 15:54:24',
            ),
            29 => 
            array (
                'id' => 85781,
                'series_id' => 72449,
                'season' => 2,
                'episode' => 9,
                'airdate' => '1998-08-21 00:00:00',
                'name' => 'Secrets',
                'description' => 'Jackson discovers that his wife has returned to Abydos, and is nine months pregnant with the son of Apophis. O\'Neill must keep the secret of the Stargate program from being uncovered.',
                'image' => 'none',
                'created_at' => '2015-02-20 15:54:24',
                'updated_at' => '2015-02-20 15:54:24',
            ),
            30 => 
            array (
                'id' => 85782,
                'series_id' => 72449,
                'season' => 2,
                'episode' => 10,
                'airdate' => '1998-09-25 00:00:00',
                'name' => 'Bane',
                'description' => 'Teal\'c is infected with deadly venom from a giant insect, and begins a terrible transformation. When he escapes the S.G.C., SG-1 must find him before Colonel Maybourne does.',
                'image' => 'none',
                'created_at' => '2015-02-20 15:54:24',
                'updated_at' => '2015-02-20 15:54:24',
            ),
            31 => 
            array (
                'id' => 85783,
                'series_id' => 72449,
                'season' => 2,
                'episode' => 11,
                'airdate' => '1998-10-02 00:00:00',
            'name' => 'The Tok\'ra (1)',
                'description' => 'SG-1 locates the Tok\'ra, a Goa\'uld resistence movement who oppose the System Lords, and attempt to form an alliance. Jacob Carter\'s cancer brings him near death.',
                'image' => 'none',
                'created_at' => '2015-02-20 15:54:24',
                'updated_at' => '2015-02-20 15:54:24',
            ),
            32 => 
            array (
                'id' => 85784,
                'series_id' => 72449,
                'season' => 2,
                'episode' => 12,
                'airdate' => '1998-10-09 00:00:00',
            'name' => 'The Tok\'ra (2)',
                'description' => 'While SG-1 tries to form an alliance with the Tok\'ra, a spy betrays the rebels to the Goa\'uld. Jacob Carter finds that the Tok\'ra may be his only hope of survival',
                'image' => 'none',
                'created_at' => '2015-02-20 15:54:24',
                'updated_at' => '2015-02-20 15:54:24',
            ),
            33 => 
            array (
                'id' => 85785,
                'series_id' => 72449,
                'season' => 2,
                'episode' => 13,
                'airdate' => '1998-10-23 00:00:00',
                'name' => 'Spirits',
                'description' => 'SG-1 finds a planet inhabited by Native American Indians, protected by spirits who are actually advanced alien shapeshifters.',
                'image' => 'none',
                'created_at' => '2015-02-20 15:54:24',
                'updated_at' => '2015-02-20 15:54:24',
            ),
            34 => 
            array (
                'id' => 85786,
                'series_id' => 72449,
                'season' => 2,
                'episode' => 14,
                'airdate' => '1998-10-30 00:00:00',
                'name' => 'Touchstone',
                'description' => 'SG-1 is accused of stealing an important weather-controlling device, sending a primative planet into chaos. The team discovers that Earth\'s second Stargate is being misused.',
                'image' => 'none',
                'created_at' => '2015-02-20 15:54:24',
                'updated_at' => '2015-02-20 15:54:24',
            ),
            35 => 
            array (
                'id' => 85787,
                'series_id' => 72449,
                'season' => 2,
                'episode' => 15,
                'airdate' => '1999-01-22 00:00:00',
                'name' => 'The Fifth Race',
                'description' => 'O\'Neill becomes the unwilling receptacle for a library of alien knowledge.',
                'image' => 'none',
                'created_at' => '2015-02-20 15:54:24',
                'updated_at' => '2015-02-20 15:54:24',
            ),
            36 => 
            array (
                'id' => 85788,
                'series_id' => 72449,
                'season' => 2,
                'episode' => 16,
                'airdate' => '1999-01-29 00:00:00',
                'name' => 'A Matter of Time',
                'description' => 'After gating to a world on the edge of a black hole, the S.G.C. cannot disengage the Stargate. All of Earth becomes endangered by the time-distorting gravity field.',
                'image' => 'none',
                'created_at' => '2015-02-20 15:54:24',
                'updated_at' => '2015-02-20 15:54:24',
            ),
            37 => 
            array (
                'id' => 85789,
                'series_id' => 72449,
                'season' => 2,
                'episode' => 17,
                'airdate' => '1999-02-05 00:00:00',
                'name' => 'Holiday',
                'description' => 'SG-1 discovers an elderly man known for developing technology to fight the Goa\'uld. Daniel is tricked into switching bodies with the man, Ma\'chello, who believes he is "owed" for all the good he has done.',
                'image' => 'none',
                'created_at' => '2015-02-20 15:54:24',
                'updated_at' => '2015-02-20 15:54:24',
            ),
            38 => 
            array (
                'id' => 85790,
                'series_id' => 72449,
                'season' => 2,
                'episode' => 18,
                'airdate' => '1999-02-12 00:00:00',
                'name' => 'Serpent\'s Song',
                'description' => 'Apophis, SG-1\'s greatest enemy, seeks sanctuary from Sokar and ends up near death in the S.G.C. infirmiry.',
                'image' => 'none',
                'created_at' => '2015-02-20 15:54:24',
                'updated_at' => '2015-02-20 15:54:24',
            ),
            39 => 
            array (
                'id' => 85791,
                'series_id' => 72449,
                'season' => 2,
                'episode' => 19,
                'airdate' => '1999-02-19 00:00:00',
                'name' => 'One False Step',
                'description' => 'A group of primitive aliens begin to fall deathly ill after SG-1 arrives.',
                'image' => 'none',
                'created_at' => '2015-02-20 15:54:24',
                'updated_at' => '2015-02-20 15:54:24',
            ),
            40 => 
            array (
                'id' => 85792,
                'series_id' => 72449,
                'season' => 2,
                'episode' => 20,
                'airdate' => '1999-02-26 00:00:00',
                'name' => 'Show and Tell',
                'description' => 'A young boy arrives through the Stargate, and warns of plot by invisible aliens to kill all of the human race in order to rob the Goa\'uld of potential hosts.',
                'image' => 'none',
                'created_at' => '2015-02-20 15:54:25',
                'updated_at' => '2015-02-20 15:54:25',
            ),
            41 => 
            array (
                'id' => 85793,
                'series_id' => 72449,
                'season' => 2,
                'episode' => 21,
                'airdate' => '1999-03-05 00:00:00',
                'name' => '1969',
                'description' => 'A cosmic accident causes SG-1 to be sent back 30 years into Earth\'s past, where they must locate the Stargate and find a way home.',
                'image' => 'none',
                'created_at' => '2015-02-20 15:54:25',
                'updated_at' => '2015-02-20 15:54:25',
            ),
            42 => 
            array (
                'id' => 85794,
                'series_id' => 72449,
                'season' => 2,
                'episode' => 22,
                'airdate' => '1999-03-12 00:00:00',
                'name' => 'Out of Mind',
                'description' => 'O\'Neill, Carter and Jackson awaken from stasis in what appears to be the S.G.C. -- almost 80 years in the future. ',
                'image' => 'none',
                'created_at' => '2015-02-20 15:54:25',
                'updated_at' => '2015-02-20 15:54:25',
            ),
            43 => 
            array (
                'id' => 85795,
                'series_id' => 72449,
                'season' => 3,
                'episode' => 1,
                'airdate' => '1999-06-25 00:00:00',
                'name' => 'Into the Fire',
                'description' => 'O\'Neill, Carter and Jackson must escape Hathor\'s clutches, while Teal\'c tries to raise a Jaffa army on Chulak. General Hammond must take desperate measures to rescue the team.
',
                'image' => 'none',
                'created_at' => '2015-02-20 15:54:25',
                'updated_at' => '2015-02-20 15:54:25',
            ),
            44 => 
            array (
                'id' => 85796,
                'series_id' => 72449,
                'season' => 3,
                'episode' => 2,
                'airdate' => '1999-07-02 00:00:00',
                'name' => 'Seth',
                'description' => 'SG-1 must find a renegade Goa\'uld who has been hiding on Earth for thousands of years.',
                'image' => 'none',
                'created_at' => '2015-02-20 15:54:25',
                'updated_at' => '2015-02-20 15:54:25',
            ),
            45 => 
            array (
                'id' => 85797,
                'series_id' => 72449,
                'season' => 3,
                'episode' => 3,
                'airdate' => '1999-07-09 00:00:00',
                'name' => 'Fair Game',
                'description' => 'The Asgard aid Earth in negotiating a nonagression treaty with the Goa\'uld System Lords.',
                'image' => 'none',
                'created_at' => '2015-02-20 15:54:25',
                'updated_at' => '2015-02-20 15:54:25',
            ),
            46 => 
            array (
                'id' => 85798,
                'series_id' => 72449,
                'season' => 3,
                'episode' => 4,
                'airdate' => '1999-07-16 00:00:00',
                'name' => 'Legacy',
                'description' => 'When Daniel goes insane, SG-1 must deal with the legacy of Machello\'s anti-Goa\'uld technology.',
                'image' => 'none',
                'created_at' => '2015-02-20 15:54:25',
                'updated_at' => '2015-02-20 15:54:25',
            ),
            47 => 
            array (
                'id' => 85799,
                'series_id' => 72449,
                'season' => 3,
                'episode' => 5,
                'airdate' => '1999-07-23 00:00:00',
                'name' => 'Learning Curve',
                'description' => 'SG-1 discovers a planet where children are used to acquire knowledge for the entire population, then discarded.',
                'image' => 'none',
                'created_at' => '2015-02-20 15:54:25',
                'updated_at' => '2015-02-20 15:54:25',
            ),
            48 => 
            array (
                'id' => 85800,
                'series_id' => 72449,
                'season' => 3,
                'episode' => 6,
                'airdate' => '1999-07-30 00:00:00',
                'name' => 'Point of View',
                'description' => 'SG-1 must free an alternate reality Earth from a Goa\'uld invasion after duplicates of Samantha Carter and Charles Kawalsky come through the quantum mirror.',
                'image' => 'none',
                'created_at' => '2015-02-20 15:54:25',
                'updated_at' => '2015-02-20 15:54:25',
            ),
            49 => 
            array (
                'id' => 85801,
                'series_id' => 72449,
                'season' => 3,
                'episode' => 7,
                'airdate' => '1999-08-06 00:00:00',
                'name' => 'Deadman Switch',
                'description' => 'SG-1 is taken captive by an alien bounty hunter with uncertain loyalties.  ',
                'image' => 'none',
                'created_at' => '2015-02-20 15:54:25',
                'updated_at' => '2015-02-20 15:54:25',
            ),
            50 =>
            array(
                'id' => 85802,
                'series_id' => 272128,
                'season' => 1,
                'episode' => 1,
                'airdate' => '1999-08-06 00:00:00',
                'name' => 'Log Horizon Episode 1',
                'description' => 'DEsc',
                'image' => 'none',
                'created_at' => '2015-02-20 15:54:25',
                'updated_at' => '2015-02-20 15:54:25',
            ),
            51 =>
            array(
                'id' => 85803,
                'series_id' => 272128,
                'season' => 1,
                'episode' => 2,
                'airdate' => '1999-08-06 00:00:00',
                'name' => 'Log Horizon Episode 2',
                'description' => 'DEsc',
                'image' => 'none',
                'created_at' => '2015-02-20 15:54:25',
                'updated_at' => '2015-02-20 15:54:25',
            ),
            52 =>
            array(
                'id' => 85804,
                'series_id' => 272128,
                'season' => 2,
                'episode' => 1,
                'airdate' => '1999-08-06 00:00:00',
                'name' => 'Log Horizon S2 Episode 1',
                'description' => 'DEsc',
                'image' => 'none',
                'created_at' => '2015-02-20 15:54:25',
                'updated_at' => '2015-02-20 15:54:25',
            ),
        ));
    }
}
